const kanjiLib = [
  {
    kanji: "一",
    meaning: "one",
    reading: "いち",
    chapter: "1",
    subchapter: "1",
  },
  {
    kanji: "二",
    meaning: "two",
    reading: "に",
    chapter: "1",
    subchapter: "1",
  },
  {
    kanji: "三",
    meaning: "three",
    reading: "さん",
    chapter: "1",
    subchapter: "1",
  },
  {
    kanji: "四",
    meaning: "four",
    reading: "し",
    chapter: "1",
    subchapter: "1",
  },
  {
    kanji: "五",
    meaning: "five",
    reading: "ご",
    chapter: "1",
    subchapter: "1",
  },
  {
    kanji: "六",
    meaning: "six",
    reading: "ろく",
    chapter: "1",
    subchapter: "1",
  },
  {
    kanji: "七",
    meaning: "seven",
    reading: "なな",
    chapter: "1",
    subchapter: "1",
  },
  {
    kanji: "八",
    meaning: "eight",
    reading: "はち",
    chapter: "1",
    subchapter: "1",
  },
  {
    kanji: "九",
    meaning: "nine",
    reading: "きゅう",
    chapter: "1",
    subchapter: "1",
  },
  {
    kanji: "十",
    meaning: "ten",
    reading: "じゅう",
    chapter: "1",
    subchapter: "1",
  },
  {
    kanji: "二十",
    meaning: "twenty",
    reading: "にじゅう",
    chapter: "1",
    subchapter: "1",
  },
  {
    kanji: "三十",
    meaning: "thirty",
    reading: "さんじゅう",
    chapter: "1",
    subchapter: "1",
  },
  {
    kanji: "四十",
    meaning: "forty",
    reading: "よんじゅう",
    chapter: "1",
    subchapter: "1",
  },
  {
    kanji: "五十",
    meaning: "fifty",
    reading: "ごじゅう",
    chapter: "1",
    subchapter: "1",
  },
  {
    kanji: "六十",
    meaning: "sixty",
    reading: "ろくじゅう",
    chapter: "1",
    subchapter: "1",
  },
  {
    kanji: "七十",
    meaning: "seventy",
    reading: "ななじゅう",
    chapter: "1",
    subchapter: "1",
  },
  {
    kanji: "八十",
    meaning: "eighty",
    reading: "はちじゅう",
    chapter: "1",
    subchapter: "1",
  },
  {
    kanji: "九十",
    meaning: "ninety",
    reading: "きゅうじゅう",
    chapter: "1",
    subchapter: "1",
  },
  {
    kanji: "一つ",
    meaning: "one thing",
    reading: "ひとつ",
    chapter: "1",
    subchapter: "1",
  },
  {
    kanji: "二つ",
    meaning: "two things",
    reading: "ふたつ",
    chapter: "1",
    subchapter: "1",
  },
  {
    kanji: "三つ",
    meaning: "three things",
    reading: "みっつ",
    chapter: "1",
    subchapter: "1",
  },
  {
    kanji: "四つ",
    meaning: "four things",
    reading: "よっつ",
    chapter: "1",
    subchapter: "1",
  },
  {
    kanji: "五つ",
    meaning: "five things",
    reading: "いつつ",
    chapter: "1",
    subchapter: "1",
  },
  {
    kanji: "六つ",
    meaning: "six things",
    reading: "むっつ",
    chapter: "1",
    subchapter: "1",
  },
  {
    kanji: "七つ",
    meaning: "seven things",
    reading: "ななつ",
    chapter: "1",
    subchapter: "1",
  },
  {
    kanji: "八つ",
    meaning: "eight things",
    reading: "やっつ",
    chapter: "1",
    subchapter: "1",
  },
  {
    kanji: "九つ",
    meaning: "nine things",
    reading: "ここのつ",
    chapter: "1",
    subchapter: "1",
  },
  {
    kanji: "百",
    meaning: "hundred",
    reading: "ひゃく",
    chapter: "1",
    subchapter: "2",
  },
  {
    kanji: "二百",
    meaning: "two hundred",
    reading: "にひゃく",
    chapter: "1",
    subchapter: "2",
  },
  {
    kanji: "三百",
    meaning: "three hundred",
    reading: "さんびゃく",
    chapter: "1",
    subchapter: "2",
  },
  {
    kanji: "四百",
    meaning: "four hundred",
    reading: "よんひゃく",
    chapter: "1",
    subchapter: "2",
  },
  {
    kanji: "五百",
    meaning: "five hundred",
    reading: "ごひゃく",
    chapter: "1",
    subchapter: "2",
  },
  {
    kanji: "六百",
    meaning: "six hundred",
    reading: "ろっぴゃく",
    chapter: "1",
    subchapter: "2",
  },
  {
    kanji: "七百",
    meaning: "seven hundred",
    reading: "ななひゃく",
    chapter: "1",
    subchapter: "2",
  },
  {
    kanji: "八百",
    meaning: "eight hundred",
    reading: "はっぴゃく",
    chapter: "1",
    subchapter: "2",
  },
  {
    kanji: "九百",
    meaning: "nine hundred",
    reading: "きゅうひゃく",
    chapter: "1",
    subchapter: "2",
  },
  {
    kanji: "千",
    meaning: "thousand",
    reading: "せん",
    chapter: "1",
    subchapter: "2",
  },
  {
    kanji: "二千",
    meaning: "two thousand",
    reading: "にせん",
    chapter: "1",
    subchapter: "2",
  },
  {
    kanji: "三千",
    meaning: "three thousand",
    reading: "さんぜん",
    chapter: "1",
    subchapter: "2",
  },
  {
    kanji: "四千",
    meaning: "four thousand",
    reading: "よんせん",
    chapter: "1",
    subchapter: "2",
  },
  {
    kanji: "五千",
    meaning: "five thousand",
    reading: "ごせん",
    chapter: "1",
    subchapter: "2",
  },
  {
    kanji: "六千",
    meaning: "six thousand",
    reading: "ろくせん",
    chapter: "1",
    subchapter: "2",
  },
  {
    kanji: "七千",
    meaning: "seven thousand",
    reading: "ななせん",
    chapter: "1",
    subchapter: "2",
  },
  {
    kanji: "八千",
    meaning: "eight thousand",
    reading: "はちせん",
    chapter: "1",
    subchapter: "2",
  },
  {
    kanji: "九千",
    meaning: "nine thousand",
    reading: "きゅうせん",
    chapter: "1",
    subchapter: "2",
  },
  {
    kanji: "万",
    meaning: "ten thousand",
    reading: "まん",
    chapter: "1",
    subchapter: "2",
  },
  {
    kanji: "二万",
    meaning: "twenty thousand",
    reading: "にまん",
    chapter: "1",
    subchapter: "2",
  },
  {
    kanji: "三万",
    meaning: "thirty thousand",
    reading: "さんまん",
    chapter: "1",
    subchapter: "2",
  },
  {
    kanji: "四万",
    meaning: "forty thousand",
    reading: "よんまん",
    chapter: "1",
    subchapter: "2",
  },
  {
    kanji: "五万",
    meaning: "fifty thousand",
    reading: "ごまん",
    chapter: "1",
    subchapter: "2",
  },
  {
    kanji: "六万",
    meaning: "sixty thousand",
    reading: "ろくまん",
    chapter: "1",
    subchapter: "2",
  },
  {
    kanji: "七万",
    meaning: "seventy thousand",
    reading: "ななまん",
    chapter: "1",
    subchapter: "2",
  },
  {
    kanji: "八万",
    meaning: "eighty thousand",
    reading: "はちまん",
    chapter: "1",
    subchapter: "2",
  },
  {
    kanji: "九万",
    meaning: "ninety thousand",
    reading: "きゅうまん",
    chapter: "1",
    subchapter: "2",
  },
  {
    kanji: "十万",
    meaning: "hundred thousand",
    reading: "じゅうまん",
    chapter: "1",
    subchapter: "2",
  },
  {
    kanji: "百万",
    meaning: "one million",
    reading: "ひゃくまん",
    chapter: "1",
    subchapter: "2",
  },
  {
    kanji: "円",
    meaning: "yen",
    reading: "えん",
    chapter: "1",
    subchapter: "2",
  },
  {
    kanji: "百円",
    meaning: "one hundred yen",
    reading: "ひゃくえん",
    chapter: "1",
    subchapter: "2",
  },
  {
    kanji: "千円",
    meaning: "one thousand yen",
    reading: "せんえん",
    chapter: "1",
    subchapter: "2",
  },
  {
    kanji: "口",
    meaning: "mouth",
    reading: "くち",
    chapter: "1",
    subchapter: "2",
  },
  {
    kanji: "目",
    meaning: "eye",
    reading: "め",
    chapter: "1",
    subchapter: "2",
  },
  {
    kanji: "日",
    meaning: "day",
    reading: "にち",
    chapter: "2",
    subchapter: "1",
  },
  {
    kanji: "月",
    meaning: "moon",
    reading: "つき",
    chapter: "2",
    subchapter: "1",
  },
  {
    kanji: "火",
    meaning: "fire",
    reading: "ひ",
    chapter: "2",
    subchapter: "1",
  },
  {
    kanji: "水",
    meaning: "water",
    reading: "みず",
    chapter: "2",
    subchapter: "1",
  },
  {
    kanji: "木",
    meaning: "tree",
    reading: "き",
    chapter: "2",
    subchapter: "1",
  },
  {
    kanji: "お金",
    meaning: "money",
    reading: "おかね",
    chapter: "2",
    subchapter: "1",
  },
  {
    kanji: "日曜日",
    meaning: "Sunday",
    reading: "にちようび",
    chapter: "2",
    subchapter: "1",
  },
  {
    kanji: "月曜日",
    meaning: "Monday",
    reading: "げつようび",
    chapter: "2",
    subchapter: "1",
  },
  {
    kanji: "火曜日",
    meaning: "Tuesday",
    reading: "かようび",
    chapter: "2",
    subchapter: "1",
  },
  {
    kanji: "水曜日",
    meaning: "Wednesday",
    reading: "すいようび",
    chapter: "2",
    subchapter: "1",
  },
  {
    kanji: "木曜日",
    meaning: "Thursday",
    reading: "もくようび",
    chapter: "2",
    subchapter: "1",
  },
  {
    kanji: "金曜日",
    meaning: "Friday",
    reading: "きんようび",
    chapter: "2",
    subchapter: "1",
  },
  {
    kanji: "土曜日",
    meaning: "Saturday",
    reading: "どようび",
    chapter: "2",
    subchapter: "1",
  },
  {
    kanji: "曜日",
    meaning: "day of the week",
    reading: "ようび",
    chapter: "2",
    subchapter: "1",
  },
  {
    kanji: "一月",
    meaning: "January",
    reading: "いちがつ",
    chapter: "2",
    subchapter: "1",
  },
  {
    kanji: "二月",
    meaning: "February",
    reading: "にがつ",
    chapter: "2",
    subchapter: "1",
  },
  {
    kanji: "三月",
    meaning: "March",
    reading: "さんがつ",
    chapter: "2",
    subchapter: "1",
  },
  {
    kanji: "四月",
    meaning: "April",
    reading: "しがつ",
    chapter: "2",
    subchapter: "1",
  },
  {
    kanji: "五月",
    meaning: "May",
    reading: "ごがつ",
    chapter: "2",
    subchapter: "1",
  },
  {
    kanji: "六月",
    meaning: "June",
    reading: "ろくがつ",
    chapter: "2",
    subchapter: "1",
  },
  {
    kanji: "七月",
    meaning: "July",
    reading: "しちがつ",
    chapter: "2",
    subchapter: "1",
  },
  {
    kanji: "八月",
    meaning: "August",
    reading: "はちがつ",
    chapter: "2",
    subchapter: "1",
  },
  {
    kanji: "九月",
    meaning: "September",
    reading: "くがつ",
    chapter: "2",
    subchapter: "1",
  },
  {
    kanji: "十月",
    meaning: "October",
    reading: "じゅうがつ",
    chapter: "2",
    subchapter: "1",
  },
  {
    kanji: "十一月",
    meaning: "November",
    reading: "じゅういちがつ",
    chapter: "2",
    subchapter: "1",
  },
  {
    kanji: "十二月",
    meaning: "December",
    reading: "じゅうにがつ",
    chapter: "2",
    subchapter: "1",
  },
  {
    kanji: "本",
    meaning: "book",
    reading: "ほん",
    chapter: "2",
    subchapter: "2",
  },
  {
    kanji: "日本",
    meaning: "Japan",
    reading: "にほん",
    chapter: "2",
    subchapter: "2",
  },
  {
    kanji: "一本",
    meaning: "one long object",
    reading: "いっぽん",
    chapter: "2",
    subchapter: "2",
  },
  {
    kanji: "二本",
    meaning: "two long objects",
    reading: "にほん",
    chapter: "2",
    subchapter: "2",
  },
  {
    kanji: "三本",
    meaning: "three long objects",
    reading: "さんぽん",
    chapter: "2",
    subchapter: "2",
  },
  {
    kanji: "四本",
    meaning: "four long objects",
    reading: "よんぽん",
    chapter: "2",
    subchapter: "2",
  },
  {
    kanji: "五本",
    meaning: "five long objects",
    reading: "ごぽん",
    chapter: "2",
    subchapter: "2",
  },
  {
    kanji: "六本",
    meaning: "six long objects",
    reading: "ろくぽん",
    chapter: "2",
    subchapter: "2",
  },
  {
    kanji: "七本",
    meaning: "seven long objects",
    reading: "ななぽん",
    chapter: "2",
    subchapter: "2",
  },
  {
    kanji: "八本",
    meaning: "eight long objects",
    reading: "はっぽん",
    chapter: "2",
    subchapter: "2",
  },
  {
    kanji: "九本",
    meaning: "nine long objects",
    reading: "きゅうぽん",
    chapter: "2",
    subchapter: "2",
  },
  {
    kanji: "十本",
    meaning: "ten long objects",
    reading: "じゅうぽん",
    chapter: "2",
    subchapter: "2",
  },
  {
    kanji: "一時",
    meaning: "one o'clock",
    reading: "いちじ",
    chapter: "2",
    subchapter: "2",
  },
  {
    kanji: "二時",
    meaning: "two o'clock",
    reading: "にじ",
    chapter: "2",
    subchapter: "2",
  },
  {
    kanji: "三時",
    meaning: "three o'clock",
    reading: "さんじ",
    chapter: "2",
    subchapter: "2",
  },
  {
    kanji: "四時",
    meaning: "four o'clock",
    reading: "よじ",
    chapter: "2",
    subchapter: "2",
  },
  {
    kanji: "五時",
    meaning: "five o'clock",
    reading: "ごじ",
    chapter: "2",
    subchapter: "2",
  },
  {
    kanji: "六時",
    meaning: "six o'clock",
    reading: "ろくじ",
    chapter: "2",
    subchapter: "2",
  },
  {
    kanji: "七時",
    meaning: "seven o'clock",
    reading: "しちじ",
    chapter: "2",
    subchapter: "2",
  },
  {
    kanji: "八時",
    meaning: "eight o'clock",
    reading: "はちじ",
    chapter: "2",
    subchapter: "2",
  },
  {
    kanji: "九時",
    meaning: "nine o'clock",
    reading: "くじ",
    chapter: "2",
    subchapter: "2",
  },
  {
    kanji: "十時",
    meaning: "ten o'clock",
    reading: "じゅうじ",
    chapter: "2",
    subchapter: "2",
  },
  {
    kanji: "十一時",
    meaning: "eleven o'clock",
    reading: "じゅういちじ",
    chapter: "2",
    subchapter: "2",
  },
  {
    kanji: "十二時",
    meaning: "twelve o'clock",
    reading: "じゅうにじ",
    chapter: "2",
    subchapter: "2",
  },
  {
    kanji: "人",
    meaning: "person",
    reading: "ひと",
    chapter: "2",
    subchapter: "2",
  },
  {
    kanji: "日本人",
    meaning: "Japanese person",
    reading: "にほんじん",
    chapter: "2",
    subchapter: "2",
  },
  {
    kanji: "一人",
    meaning: "one person",
    reading: "ひとり",
    chapter: "2",
    subchapter: "2",
  },
  {
    kanji: "二人",
    meaning: "two people",
    reading: "ふたり",
    chapter: "2",
    subchapter: "2",
  },
  {
    kanji: "三人",
    meaning: "three people",
    reading: "さんにん",
    chapter: "2",
    subchapter: "2",
  },
  {
    kanji: "四人",
    meaning: "four people",
    reading: "よんにん",
    chapter: "2",
    subchapter: "2",
  },
  {
    kanji: "五人",
    meaning: "five people",
    reading: "ごにん",
    chapter: "2",
    subchapter: "2",
  },
  {
    kanji: "一人で",
    meaning: "alone",
    reading: "ひとりで",
    chapter: "2",
    subchapter: "2",
  },
  {
    kanji: "今",
    meaning: "now",
    reading: "いま",
    chapter: "2",
    subchapter: "2",
  },
  {
    kanji: "今月",
    meaning: "this month",
    reading: "こんげつ",
    chapter: "2",
    subchapter: "2",
  },
  {
    kanji: "今日",
    meaning: "today",
    reading: "きょう",
    chapter: "2",
    subchapter: "2",
  },
  {
    kanji: "一時半",
    meaning: "one thirty",
    reading: "いちじはん",
    chapter: "2",
    subchapter: "2",
  },
  {
    kanji: "二時半",
    meaning: "two thirty",
    reading: "にじはん",
    chapter: "2",
    subchapter: "2",
  },
  {
    kanji: "三時半",
    meaning: "three thirty",
    reading: "さんじはん",
    chapter: "2",
    subchapter: "2",
  },
  {
    kanji: "五分",
    meaning: "five minutes",
    reading: "ごふん",
    chapter: "2",
    subchapter: "2",
  },
  {
    kanji: "十分",
    meaning: "ten minutes",
    reading: "じゅうふん",
    chapter: "2",
    subchapter: "2",
  },
  {
    kanji: "半分",
    meaning: "half",
    reading: "はんぶん",
    chapter: "2",
    subchapter: "2",
  },
  {
    kanji: "分かる",
    meaning: "to understand",
    reading: "わかる",
    chapter: "2",
    subchapter: "2",
  },
  {
    kanji: "上",
    meaning: "up",
    reading: "うえ",
    chapter: "3",
    subchapter: "1",
  },
  {
    kanji: "上げる",
    meaning: "to raise",
    reading: "あげる",
    chapter: "3",
    subchapter: "1",
  },
  {
    kanji: "下",
    meaning: "down",
    reading: "した",
    chapter: "3",
    subchapter: "1",
  },
  {
    kanji: "下げる",
    meaning: "to lower",
    reading: "さげる",
    chapter: "3",
    subchapter: "1",
  },
  {
    kanji: "中",
    meaning: "middle",
    reading: "なか",
    chapter: "3",
    subchapter: "1",
  },
  {
    kanji: "外",
    meaning: "outside",
    reading: "そと",
    chapter: "3",
    subchapter: "1",
  },
  {
    kanji: "右",
    meaning: "right",
    reading: "みぎ",
    chapter: "3",
    subchapter: "1",
  },
  {
    kanji: "左",
    meaning: "left",
    reading: "ひだり",
    chapter: "3",
    subchapter: "1",
  },
  {
    kanji: "前",
    meaning: "front",
    reading: "まえ",
    chapter: "3",
    subchapter: "1",
  },
  {
    kanji: "後ろ",
    meaning: "back",
    reading: "うしろ",
    chapter: "3",
    subchapter: "1",
  },
  {
    kanji: "後で",
    meaning: "later",
    reading: "あとで",
    chapter: "3",
    subchapter: "1",
  },
  {
    kanji: "午前",
    meaning: "morning",
    reading: "ごぜん",
    chapter: "3",
    subchapter: "2",
  },
  {
    kanji: "午後",
    meaning: "afternoon",
    reading: "ごご",
    chapter: "3",
    subchapter: "2",
  },
  {
    kanji: "午前中",
    meaning: "in the morning",
    reading: "ごぜんちゅう",
    chapter: "3",
    subchapter: "2",
  },
  {
    kanji: "門",
    meaning: "gate",
    reading: "もん",
    chapter: "3",
    subchapter: "2",
  },
  {
    kanji: "間",
    meaning: "between",
    reading: "あいだ",
    chapter: "3",
    subchapter: "2",
  },
  {
    kanji: "時間",
    meaning: "time",
    reading: "じかん",
    chapter: "3",
    subchapter: "2",
  },
  {
    kanji: "一時間",
    meaning: "one hour",
    reading: "いちじかん",
    chapter: "3",
    subchapter: "2",
  },
  {
    kanji: "二時間",
    meaning: "two hours",
    reading: "にじかん",
    chapter: "3",
    subchapter: "2",
  },
  {
    kanji: "三時間",
    meaning: "three hours",
    reading: "さんじかん",
    chapter: "3",
    subchapter: "2",
  },
  {
    kanji: "四時間",
    meaning: "four hours",
    reading: "よんじかん",
    chapter: "3",
    subchapter: "2",
  },
  {
    kanji: "五時間",
    meaning: "five hours",
    reading: "ごじかん",
    chapter: "3",
    subchapter: "2",
  },
  {
    kanji: "六時間",
    meaning: "six hours",
    reading: "ろくじかん",
    chapter: "3",
    subchapter: "2",
  },
  {
    kanji: "七時間",
    meaning: "seven hours",
    reading: "ななじかん",
    chapter: "3",
    subchapter: "2",
  },
  {
    kanji: "八時間",
    meaning: "eight hours",
    reading: "はちじかん",
    chapter: "3",
    subchapter: "2",
  },
  {
    kanji: "九時間",
    meaning: "nine hours",
    reading: "くじかん",
    chapter: "3",
    subchapter: "2",
  },
  {
    kanji: "東",
    meaning: "east",
    reading: "ひがし",
    chapter: "3",
    subchapter: "2",
  },
  {
    kanji: "東口",
    meaning: "east exit",
    reading: "ひがしぐち",
    chapter: "3",
    subchapter: "2",
  },
  {
    kanji: "中東",
    meaning: "middle east",
    reading: "ちゅうとう",
    chapter: "3",
    subchapter: "2",
  },
  {
    kanji: "西",
    meaning: "west",
    reading: "にし",
    chapter: "3",
    subchapter: "2",
  },
  {
    kanji: "西口",
    meaning: "west exit",
    reading: "にしぐち",
    chapter: "3",
    subchapter: "2",
  },
  {
    kanji: "南",
    meaning: "south",
    reading: "みなみ",
    chapter: "3",
    subchapter: "2",
  },
  {
    kanji: "南口",
    meaning: "south exit",
    reading: "みなみぐち",
    chapter: "3",
    subchapter: "2",
  },
  {
    kanji: "南東",
    meaning: "southeast",
    reading: "なんとう",
    chapter: "3",
    subchapter: "2",
  },
  {
    kanji: "北",
    meaning: "north",
    reading: "きた",
    chapter: "3",
    subchapter: "2",
  },
  {
    kanji: "北口",
    meaning: "north exit",
    reading: "きたぐち",
    chapter: "3",
    subchapter: "2",
  },
  {
    kanji: "田中さん",
    meaning: "tanaka",
    reading: "たなかさん",
    chapter: "4",
    subchapter: "1",
  },
  {
    kanji: "力",
    meaning: "power",
    reading: "ちから",
    chapter: "4",
    subchapter: "1",
  },
  {
    kanji: "男の人",
    meaning: "man",
    reading: "おとこのひと",
    chapter: "4",
    subchapter: "1",
  },
  {
    kanji: "女の人",
    meaning: "woman",
    reading: "おんなのひと",
    chapter: "4",
    subchapter: "1",
  },
  {
    kanji: "男の子",
    meaning: "boy",
    reading: "おとこのこ",
    chapter: "4",
    subchapter: "1",
  },
  {
    kanji: "女の子",
    meaning: "girl",
    reading: "おんなのこ",
    chapter: "4",
    subchapter: "1",
  },
  {
    kanji: "学生",
    meaning: "student",
    reading: "がくせい",
    chapter: "4",
    subchapter: "1",
  },
  {
    kanji: "生まれる",
    meaning: "to be born",
    reading: "うまれる",
    chapter: "4",
    subchapter: "1",
  },
  {
    kanji: "生きる",
    meaning: "to live",
    reading: "いきる",
    chapter: "4",
    subchapter: "1",
  },
  {
    kanji: "先生",
    meaning: "teacher",
    reading: "せんせい",
    chapter: "4",
    subchapter: "1",
  },
  {
    kanji: "先月",
    meaning: "last month",
    reading: "せんげつ",
    chapter: "4",
    subchapter: "1",
  },
  {
    kanji: "何",
    meaning: "what",
    reading: "なん",
    chapter: "4",
    subchapter: "1",
  },
  {
    kanji: "何か",
    meaning: "something",
    reading: "なにか",
    chapter: "4",
    subchapter: "1",
  },
  {
    kanji: "何人",
    meaning: "how many people",
    reading: "なんにん",
    chapter: "4",
    subchapter: "1",
  },
  {
    kanji: "何時",
    meaning: "what time",
    reading: "なんじ",
    chapter: "4",
    subchapter: "1",
  },
  {
    kanji: "父",
    meaning: "my father",
    reading: "ちち",
    chapter: "4",
    subchapter: "2",
  },
  {
    kanji: "お父さん",
    meaning: "father",
    reading: "おとうさん",
    chapter: "4",
    subchapter: "2",
  },
  {
    kanji: "父の日",
    meaning: "father's day",
    reading: "ちちのひ",
    chapter: "4",
    subchapter: "2",
  },
  {
    kanji: "母",
    meaning: "my mother",
    reading: "はは",
    chapter: "4",
    subchapter: "2",
  },
  {
    kanji: "お母さん",
    meaning: "mother",
    reading: "おかあさん",
    chapter: "4",
    subchapter: "2",
  },
  {
    kanji: "母の日",
    meaning: "mother's day",
    reading: "ははのひ",
    chapter: "4",
    subchapter: "2",
  },
  {
    kanji: "一年生",
    meaning: "first grade",
    reading: "いちねんせい",
    chapter: "4",
    subchapter: "2",
  },
  {
    kanji: "二年生",
    meaning: "second grade",
    reading: "にねんせい",
    chapter: "4",
    subchapter: "2",
  },
  {
    kanji: "三年生",
    meaning: "third grade",
    reading: "さんねんせい",
    chapter: "4",
    subchapter: "2",
  },
  {
    kanji: "四年生",
    meaning: "fourth grade",
    reading: "よんねんせい",
    chapter: "4",
    subchapter: "2",
  },
  {
    kanji: "五年生",
    meaning: "fifth grade",
    reading: "ごねんせい",
    chapter: "4",
    subchapter: "2",
  },
  {
    kanji: "今生",
    meaning: "this year",
    reading: "こんねん",
    chapter: "4",
    subchapter: "2",
  },
  {
    kanji: "生",
    meaning: "year",
    reading: "ねん",
    chapter: "4",
    subchapter: "2",
  },
  {
    kanji: "去年",
    meaning: "last year",
    reading: "きょねん",
    chapter: "4",
    subchapter: "2",
  },
  {
    kanji: "毎日",
    meaning: "every day",
    reading: "まいにち",
    chapter: "4",
    subchapter: "2",
  },
  {
    kanji: "毎月",
    meaning: "every month",
    reading: "まいつき",
    chapter: "4",
    subchapter: "2",
  },
  {
    kanji: "毎年",
    meaning: "every year",
    reading: "まいとし",
    chapter: "4",
    subchapter: "2",
  },
  {
    kanji: "見る",
    meaning: "to see",
    reading: "みる",
    chapter: "5",
    subchapter: "1",
  },
  {
    kanji: "見せる",
    meaning: "to show",
    reading: "みせる",
    chapter: "5",
    subchapter: "1",
  },
  {
    kanji: "見える",
    meaning: "to be visible",
    reading: "みえる",
    chapter: "5",
    subchapter: "1",
  },
  {
    kanji: "行く",
    meaning: "to go",
    reading: "いく",
    chapter: "5",
    subchapter: "1",
  },
  {
    kanji: "お米",
    meaning: "rice",
    reading: "おこめ",
    chapter: "5",
    subchapter: "1",
  },
  {
    kanji: "来る",
    meaning: "to come",
    reading: "くる",
    chapter: "5",
    subchapter: "1",
  },
  {
    kanji: "来ます",
    meaning: "to come",
    reading: "きます",
    chapter: "5",
    subchapter: "1",
  },
  {
    kanji: "来ない",
    meaning: "not to come",
    reading: "こない",
    chapter: "5",
    subchapter: "1",
  },
  {
    kanji: "来年",
    meaning: "next year",
    reading: "らいねん",
    chapter: "5",
    subchapter: "1",
  },
  {
    kanji: "食べる",
    meaning: "to eat",
    reading: "たべる",
    chapter: "5",
    subchapter: "1",
  },
  {
    kanji: "飲む",
    meaning: "to drink",
    reading: "のむ",
    chapter: "5",
    subchapter: "1",
  },
  {
    kanji: "会う",
    meaning: "to meet",
    reading: "あう",
    chapter: "5",
    subchapter: "1",
  },
  {
    kanji: "耳",
    meaning: "ear",
    reading: "みみ",
    chapter: "5",
    subchapter: "2",
  },
  {
    kanji: "聞く",
    meaning: "to listen",
    reading: "きく",
    chapter: "5",
    subchapter: "2",
  },
  {
    kanji: "聞こえる",
    meaning: ["can be heard", "to be audible"],
    reading: "きこえる",
    chapter: "5",
    subchapter: "2",
  },
  {
    kanji: "言う",
    meaning: "to say",
    reading: "いう",
    chapter: "5",
    subchapter: "2",
  },
  {
    kanji: "話す",
    meaning: "to talk",
    reading: "はなす",
    chapter: "5",
    subchapter: "2",
  },
  {
    kanji: "話",
    meaning: "story",
    reading: "はなし",
    chapter: "5",
    subchapter: "2",
  },
  {
    kanji: "会話",
    meaning: "conversation",
    reading: "かいわ",
    chapter: "5",
    subchapter: "2",
  },
  {
    kanji: "立つ",
    meaning: "to stand",
    reading: "たつ",
    chapter: "5",
    subchapter: "2",
  },
  {
    kanji: "待つ",
    meaning: "to wait",
    reading: "まつ",
    chapter: "5",
    subchapter: "2",
  },
  {
    kanji: "今週",
    meaning: "this week",
    reading: "こんしゅう",
    chapter: "5",
    subchapter: "2",
  },
  {
    kanji: "来週",
    meaning: "next week",
    reading: "らいしゅう",
    chapter: "5",
    subchapter: "2",
  },
  {
    kanji: "先週",
    meaning: "last week",
    reading: "せんしゅう",
    chapter: "5",
    subchapter: "2",
  },
  {
    kanji: "毎週",
    meaning: "every week",
    reading: "まいしゅう",
    chapter: "5",
    subchapter: "2",
  },
  {
    kanji: "一週間",
    meaning: "one week",
    reading: "いっしゅうかん",
    chapter: "5",
    subchapter: "2",
  },
  {
    kanji: "大きい",
    meaning: "big",
    reading: "おおきい",
    chapter: "6",
    subchapter: "1",
  },
  {
    kanji: "大学",
    meaning: "college",
    reading: "だいがく",
    chapter: "6",
    subchapter: "1",
  },
  {
    kanji: "大学生",
    meaning: "college student",
    reading: "だいがくせい",
    chapter: "6",
    subchapter: "1",
  },
  {
    kanji: "大人",
    meaning: "adult",
    reading: "おとな",
    chapter: "6",
    subchapter: "1",
  },
  {
    kanji: "小さい",
    meaning: "small",
    reading: "ちいさい",
    chapter: "6",
    subchapter: "1",
  },
  {
    kanji: "小学生",
    meaning: "elementary school student",
    reading: "しょうがくせい",
    chapter: "6",
    subchapter: "1",
  },
  {
    kanji: "高い",
    meaning: "high",
    reading: "たかい",
    chapter: "6",
    subchapter: "1",
  },
  {
    kanji: "安い",
    meaning: "cheap",
    reading: "やすい",
    chapter: "6",
    subchapter: "1",
  },
  {
    kanji: "新しい",
    meaning: "new",
    reading: "あたらしい",
    chapter: "6",
    subchapter: "1",
  },
  {
    kanji: "新聞",
    meaning: "newspaper",
    reading: "しんぶん",
    chapter: "6",
    subchapter: "1",
  },
  {
    kanji: "古い",
    meaning: "old",
    reading: "ふるい",
    chapter: "6",
    subchapter: "1",
  },
  {
    kanji: "元気",
    meaning: "energetic",
    reading: "げんき",
    chapter: "6",
    subchapter: "1",
  },
  {
    kanji: "気をつける",
    meaning: "to be careful",
    reading: "きをつける",
    chapter: "6",
    subchapter: "1",
  },
  {
    kanji: "多い",
    meaning: "many",
    reading: "おおい",
    chapter: "6",
    subchapter: "2",
  },
  {
    kanji: "少し",
    meaning: "a little",
    reading: "すこし",
    chapter: "6",
    subchapter: "2",
  },
  {
    kanji: "少ない",
    meaning: "few",
    reading: "すくない",
    chapter: "6",
    subchapter: "2",
  },
  {
    kanji: "広い",
    meaning: "wide",
    reading: "ひろい",
    chapter: "6",
    subchapter: "2",
  },
  {
    kanji: "早い",
    meaning: "early",
    reading: "はやい",
    chapter: "6",
    subchapter: "2",
  },
  {
    kanji: "早く",
    meaning: "early",
    reading: "はやく",
    chapter: "6",
    subchapter: "2",
  },
  {
    kanji: "長い",
    meaning: "long",
    reading: "ながい",
    chapter: "6",
    subchapter: "2",
  },
  {
    kanji: "明るい",
    meaning: "bright",
    reading: "あかるい",
    chapter: "6",
    subchapter: "2",
  },
  {
    kanji: "明日",
    meaning: "tomorrow",
    reading: "あした",
    chapter: "6",
    subchapter: "2",
  },
  {
    kanji: "好き",
    meaning: "favourite",
    reading: "すき",
    chapter: "6",
    subchapter: "2",
  },
  {
    kanji: "大好き",
    meaning: "very favourite",
    reading: "だいすき",
    chapter: "6",
    subchapter: "2",
  },
  {
    kanji: "友だち",
    meaning: "friend",
    reading: "ともだち",
    chapter: "6",
    subchapter: "2",
  },
  {
    kanji: "入る",
    meaning: "to enter",
    reading: "はいる",
    chapter: "7",
    subchapter: "1",
  },
  {
    kanji: "入れる",
    meaning: "to put in",
    reading: "いれる",
    chapter: "7",
    subchapter: "1",
  },
  {
    kanji: "入り口",
    meaning: "entrance",
    reading: "いりぐち",
    chapter: "7",
    subchapter: "1",
  },
  {
    kanji: "入学する",
    meaning: "to enter a school",
    reading: "にゅがくする",
    chapter: "7",
    subchapter: "1",
  },
  {
    kanji: "出る",
    meaning: "to exit",
    reading: "でる",
    chapter: "7",
    subchapter: "1",
  },
  {
    kanji: "出かける",
    meaning: "to go out",
    reading: "でかける",
    chapter: "7",
    subchapter: "1",
  },
  {
    kanji: "出す",
    meaning: "to take something out",
    reading: "だす",
    chapter: "7",
    subchapter: "1",
  },
  {
    kanji: "出口",
    meaning: "exit",
    reading: "しゅつぐち",
    chapter: "7",
    subchapter: "1",
  },
  {
    kanji: "出口",
    meaning: "exit",
    reading: "しゅつぐち",
    chapter: "7",
    subchapter: "1",
  },
  {
    kanji: "つくば市",
    meaning: "Tsukuba City",
    reading: "つくばし",
    chapter: "7",
    subchapter: "1",
  },
  {
    kanji: "市長",
    meaning: "Mayor",
    reading: "しちょう",
    chapter: "7",
    subchapter: "1",
  },
  {
    kanji: "町",
    meaning: "town",
    reading: "まち",
    chapter: "7",
    subchapter: "1",
  },
  {
    kanji: "村",
    meaning: "village",
    reading: "むら",
    chapter: "7",
    subchapter: "1",
  },
  {
    kanji: "雨",
    meaning: "rain",
    reading: "あめ",
    chapter: "7",
    subchapter: "1",
  },
  {
    kanji: "電気",
    meaning: "electricity",
    reading: "でんき",
    chapter: "7",
    subchapter: "1",
  },
  {
    kanji: "電話",
    meaning: "telephone",
    reading: "でんわ",
    chapter: "7",
    subchapter: "1",
  },
  {
    kanji: "電車",
    meaning: "train",
    reading: "でんしゃ",
    chapter: "7",
    subchapter: "1",
  },
  {
    kanji: "車",
    meaning: "car",
    reading: "くるま",
    chapter: "7",
    subchapter: "1",
  },
  {
    kanji: "馬",
    meaning: "horse",
    reading: "うま",
    chapter: "7",
    subchapter: "2",
  },
  {
    kanji: "駅",
    meaning: "station",
    reading: "えき",
    chapter: "7",
    subchapter: "2",
  },
  {
    kanji: "会社",
    meaning: "company",
    reading: "かいしゃ",
    chapter: "7",
    subchapter: "2",
  },
  {
    kanji: "社会",
    meaning: "society",
    reading: "しゃかい",
    chapter: "7",
    subchapter: "2",
  },
  {
    kanji: "社長",
    meaning: "company president",
    reading: "しゃちょう",
    chapter: "7",
    subchapter: "2",
  },
  {
    kanji: "学校",
    meaning: "school",
    reading: "がっこう",
    chapter: "7",
    subchapter: "2",
  },
  {
    kanji: "高校",
    meaning: "high school",
    reading: "こうこう",
    chapter: "7",
    subchapter: "2",
  },
  {
    kanji: "中学校",
    meaning: "junior high school",
    reading: "ちゅうがっこう",
    chapter: "7",
    subchapter: "2",
  },
  {
    kanji: "小学校",
    meaning: "elementary school",
    reading: "しょうがっこう",
    chapter: "7",
    subchapter: "2",
  },
  {
    kanji: "校長",
    meaning: "principal",
    reading: "こうちょう",
    chapter: "7",
    subchapter: "2",
  },
  {
    kanji: "店",
    meaning: "shop",
    reading: "みせ",
    chapter: "7",
    subchapter: "2",
  },
  {
    kanji: "銀行",
    meaning: "bank",
    reading: "ぎんこう",
    chapter: "7",
    subchapter: "2",
  },
  {
    kanji: "病気",
    meaning: "illness",
    reading: "びょうき",
    chapter: "7",
    subchapter: "2",
  },
  {
    kanji: "病院",
    meaning: "hospital",
    reading: "びょういん",
    chapter: "7",
    subchapter: "2",
  },
  {
    kanji: "入院する",
    meaning: "to be hospitalized",
    reading: "にゅういんする",
    chapter: "7",
    subchapter: "2",
  },
  {
    kanji: "大学院",
    meaning: "graduate school",
    reading: "だいがくいん",
    chapter: "7",
    subchapter: "2",
  },
  {
    kanji: "大学院生",
    meaning: "graduate student",
    reading: "だいがくいんせい",
    chapter: "7",
    subchapter: "2",
  },
  {
    kanji: "休む",
    meaning: "to rest",
    reading: "やすむ",
    chapter: "8",
    subchapter: "1",
  },
  {
    kanji: "休み",
    meaning: "holiday",
    reading: "やすみ",
    chapter: "8",
    subchapter: "1",
  },
  {
    kanji: "走る",
    meaning: "to run",
    reading: "はしる",
    chapter: "8",
    subchapter: "1",
  },
  {
    kanji: "起きる",
    meaning: "to get up",
    reading: "おきる",
    chapter: "8",
    subchapter: "1",
  },
  {
    kanji: "起こす",
    meaning: "to wake someone up",
    reading: "おこす",
    chapter: "8",
    subchapter: "1",
  },
  {
    kanji: "貝",
    meaning: "shellfish",
    reading: "かい",
    chapter: "8",
    subchapter: "1",
  },
  {
    kanji: "買う",
    meaning: "to buy",
    reading: "かう",
    chapter: "8",
    subchapter: "1",
  },
  {
    kanji: "売る",
    meaning: "to sell",
    reading: "うる",
    chapter: "8",
    subchapter: "1",
  },
  {
    kanji: "読む",
    meaning: "to read",
    reading: "よむ",
    chapter: "8",
    subchapter: "1",
  },
  {
    kanji: "書く",
    meaning: "to write",
    reading: "かく",
    chapter: "8",
    subchapter: "1",
  },
  {
    kanji: "帰る",
    meaning: "to return",
    reading: "かえる",
    chapter: "8",
    subchapter: "2",
  },
  {
    kanji: "虫",
    meaning: "insect",
    reading: "むし",
    chapter: "8",
    subchapter: "2",
  },
  {
    kanji: "強い",
    meaning: "strong",
    reading: "つよい",
    chapter: "8",
    subchapter: "2",
  },
  {
    kanji: "勉強する",
    meaning: "to study",
    reading: "べんきょうする",
    chapter: "8",
    subchapter: "2",
  },
  {
    kanji: "持つ",
    meaning: "to hold",
    reading: "もつ",
    chapter: "8",
    subchapter: "2",
  },
  {
    kanji: "お金持ち",
    meaning: "rich person",
    reading: "おかねもち",
    chapter: "8",
    subchapter: "2",
  },
  {
    kanji: "気持ち",
    meaning: "feeling",
    reading: "きもち",
    chapter: "8",
    subchapter: "2",
  },
  {
    kanji: "名前",
    meaning: "name",
    reading: "なまえ",
    chapter: "8",
    subchapter: "2",
  },
  {
    kanji: "日本語",
    meaning: "japanese language",
    reading: "にほんご",
    chapter: "8",
    subchapter: "2",
  },
  {
    kanji: "中国語",
    meaning: "chinese language",
    reading: "ちゅうご",
    chapter: "8",
    subchapter: "2",
  },
  {
    kanji: "春",
    meaning: "spring",
    reading: "はる",
    chapter: "9",
    subchapter: "1",
  },
  {
    kanji: "春休み",
    meaning: "spring vacation",
    reading: "はるやすみ",
    chapter: "9",
    subchapter: "1",
  },
  {
    kanji: "夏",
    meaning: "summer",
    reading: "なつ",
    chapter: "9",
    subchapter: "1",
  },
  {
    kanji: "夏休み",
    meaning: "summer vacation",
    reading: "なつやすみ",
    chapter: "9",
    subchapter: "1",
  },
  {
    kanji: "秋",
    meaning: "autumn",
    reading: "あき",
    chapter: "9",
    subchapter: "1",
  },
  {
    kanji: "冬",
    meaning: "winter",
    reading: "ふゆ",
    chapter: "9",
    subchapter: "1",
  },
  {
    kanji: "冬休み",
    meaning: "winter vacation",
    reading: "ふゆやすみ",
    chapter: "9",
    subchapter: "1",
  },
  {
    kanji: "朝",
    meaning: "morning",
    reading: "あさ",
    chapter: "9",
    subchapter: "1",
  },
  {
    kanji: "今朝",
    meaning: "this morning",
    reading: "けさ",
    chapter: "9",
    subchapter: "1",
  },
  {
    kanji: "昼",
    meaning: "noon",
    reading: "ひる",
    chapter: "9",
    subchapter: "1",
  },
  {
    kanji: "昼間",
    meaning: "daytime",
    reading: "ひるま",
    chapter: "9",
    subchapter: "1",
  },
  {
    kanji: "昼休み",
    meaning: "lunch break",
    reading: "ひるやすみ",
    chapter: "9",
    subchapter: "1",
  },
  {
    kanji: "方",
    meaning: "way of doing",
    reading: "かた",
    chapter: "9",
    subchapter: "1",
  },
  {
    kanji: "夕方",
    meaning: "early evening",
    reading: "ゆうがた",
    chapter: "9",
    subchapter: "1",
  },
  {
    kanji: "晩",
    meaning: "night",
    reading: "ばん",
    chapter: "9",
    subchapter: "2",
  },
  {
    kanji: "今晩",
    meaning: "tonight",
    reading: "こんばん",
    chapter: "9",
    subchapter: "2",
  },
  {
    kanji: "毎晩",
    meaning: "every night",
    reading: "まいばん",
    chapter: "9",
    subchapter: "2",
  },
  {
    kanji: "夜",
    meaning: "night",
    reading: "よる",
    chapter: "9",
    subchapter: "2",
  },
  {
    kanji: "今夜",
    meaning: "tonight",
    reading: "こんや",
    chapter: "9",
    subchapter: "2",
  },
  {
    kanji: "夜中",
    meaning: "midnight",
    reading: "よなか",
    chapter: "9",
    subchapter: "2",
  },
  {
    kanji: "心",
    meaning: "heart",
    reading: "こころ",
    chapter: "9",
    subchapter: "2",
  },
  {
    kanji: "安心する",
    meaning: "to be relieved",
    reading: "あんしんする",
    chapter: "9",
    subchapter: "2",
  },
  {
    kanji: "手",
    meaning: "hand",
    reading: "て",
    chapter: "9",
    subchapter: "2",
  },
  {
    kanji: "下手な",
    meaning: "bad at",
    reading: "へたな",
    chapter: "9",
    subchapter: "2",
  },
  {
    kanji: "上手な",
    meaning: "good at",
    reading: "じょうずな",
    chapter: "9",
    subchapter: "2",
  },
  {
    kanji: "足",
    meaning: "foot",
    reading: "あし",
    chapter: "9",
    subchapter: "2",
  },
  {
    kanji: "足りる",
    meaning: "to be sufficient",
    reading: "たりる",
    chapter: "9",
    subchapter: "2",
  },
  {
    kanji: "足す",
    meaning: "to add",
    reading: "たす",
    chapter: "9",
    subchapter: "2",
  },
  {
    kanji: "体",
    meaning: "body",
    reading: "からだ",
    chapter: "9",
    subchapter: "2",
  },
  {
    kanji: "首",
    meaning: "neck",
    reading: "くび",
    chapter: "9",
    subchapter: "2",
  },
  {
    kanji: "道",
    meaning: "road",
    reading: "みち",
    chapter: "9",
    subchapter: "2",
  },
];
/*
TEMPLATE:
{
  kanji: "",
  meaning: "",
  reading: "",
  chapter: "",
  subchapter: "",
},
*/
