const kanjiLib = [
    {"kanji": "一", "meaning": "one", "reading": "いち", "chapter": "1", "subchapter": "1"},
    {"kanji": "二", "meaning": "two", "reading": "に", "chapter": "1", "subchapter": "1"},
    {"kanji": "三", "meaning": "three", "reading": "さん", "chapter": "1", "subchapter": "1"},
    {"kanji": "四", "meaning": "four", "reading": "よん", "chapter": "1", "subchapter": "1"},
    {"kanji": "五", "meaning": "five", "reading": "ご", "chapter": "1", "subchapter": "1"},
    {"kanji": "六", "meaning": "six", "reading": "ろく", "chapter": "1", "subchapter": "1"},
    {"kanji": "七", "meaning": "seven", "reading": "なな", "chapter": "1", "subchapter": "1"},
    {"kanji": "八", "meaning": "eight", "reading": "はち", "chapter": "1", "subchapter": "1"},
    {"kanji": "九", "meaning": "nine", "reading": "きゅう", "chapter": "1", "subchapter": "1"},
    {"kanji": "十", "meaning": "ten", "reading": "じゅう", "chapter": "1", "subchapter": "1"},
    {"kanji": "二十", "meaning": "twenty", "reading": "はたち", "chapter": "1", "subchapter": "1"},
    {"kanji": "三十", "meaning": "thirty", "reading": "さんじゅう", "chapter": "1", "subchapter": "1"},
    {"kanji": "四十", "meaning": "forty", "reading": "よんじゅう", "chapter": "1", "subchapter": "1"},
    {"kanji": "五十", "meaning": "fifty", "reading": "ごじゅう", "chapter": "1", "subchapter": "1"},
    {"kanji": "六万", "meaning": "sixty", "reading": "ろくじゅう", "chapter": "1", "subchapter": "1"},
    {"kanji": "七十", "meaning": "seventy", "reading": "ななじゅう", "chapter": "1", "subchapter": "1"},
    {"kanji": "八十", "meaning": "eighty", "reading": "はちじゅう", "chapter": "1", "subchapter": "1"},
    {"kanji": "九十", "meaning": "ninety", "reading": "きゅうじゅう", "chapter": "1", "subchapter": "1"},
    {"kanji": "一つ", "meaning": "one thing", "reading": "ひとつ", "chapter": "1", "subchapter": "1"},
    {"kanji": "二つ", "meaning": "two things", "reading": "ふたつ", "chapter": "1", "subchapter": "1"},
    {"kanji": "三つ", "meaning": "three things", "reading": "さんつ", "chapter": "1", "subchapter": "1"},
    {"kanji": "四つ", "meaning": "four things", "reading": "よっつ", "chapter": "1", "subchapter": "1"},
    {"kanji": "五つ", "meaning": "five things", "reading": "ごつ", "chapter": "1", "subchapter": "1"},
    {"kanji": "六つ", "meaning": "six things", "reading": "むつ", "chapter": "1", "subchapter": "1"},
    {"kanji": "七つ", "meaning": "seven things", "reading": "ななつ", "chapter": "1", "subchapter": "1"},
    {"kanji": "八つ", "meaning": "eight things", "reading": "やっつ", "chapter": "1", "subchapter": "1"},
    {"kanji": "九つ", "meaning": "nine things", "reading": "ここのつ", "chapter": "1", "subchapter": "1"},
    {"kanji": "百", "meaning": "hundred", "reading": "ひゃく", "chapter": "1", "subchapter": "2"},
    {"kanji": "二百", "meaning": "two hundred", "reading": "にひゃく", "chapter": "1", "subchapter": "2"},
    {"kanji": "三百", "meaning": "three hundred", "reading": "さんびゃく", "chapter": "1", "subchapter": "2"},
    {"kanji": "四百", "meaning": "four hundred", "reading": "よんひゃく", "chapter": "1", "subchapter": "2"},
    {"kanji": "五百", "meaning": "five hundred", "reading": "ごひゃく", "chapter": "1", "subchapter": "2"},
    {"kanji": "六百", "meaning": "six hundred", "reading": "ろっぴゃく", "chapter": "1", "subchapter": "2"},
    {"kanji": "七百", "meaning": "seven hundred", "reading": "ななひゃく", "chapter": "1", "subchapter": "2"},
    {"kanji": "八百", "meaning": "eight hundred", "reading": "はっぴゃく", "chapter": "1", "subchapter": "2"},
    {"kanji": "九百", "meaning": "nine hundred", "reading": "きゅうひゃく", "chapter": "1", "subchapter": "2"},
    {"kanji": "千", "meaning": "thousand", "reading": "せん", "chapter": "1", "subchapter": "2"},
    {"kanji": "二千", "meaning": "two thousand", "reading": "にせん", "chapter": "1", "subchapter": "2"},
    {"kanji": "三千", "meaning": "three thousand", "reading": "さんぜん", "chapter": "1", "subchapter": "2"},
    {"kanji": "四千", "meaning": "four thousand", "reading": "よんせん", "chapter": "1", "subchapter": "2"},
    {"kanji": "五千", "meaning": "five thousand", "reading": "ごせん", "chapter": "1", "subchapter": "2"},
    {"kanji": "六千", "meaning": "six thousand", "reading": "ろくせん", "chapter": "1", "subchapter": "2"},
    {"kanji": "七千", "meaning": "seven thousand", "reading": "ななせん", "chapter": "1", "subchapter": "2"},
    {"kanji": "八千", "meaning": "eight thousand", "reading": "はちせん", "chapter": "1", "subchapter": "2"},
    {"kanji": "九千", "meaning": "nine thousand", "reading": "きゅうせん", "chapter": "1", "subchapter": "2"},
    {"kanji": "万", "meaning": "ten thousand", "reading": "まん", "chapter": "1", "subchapter": "2"},
    {"kanji": "二万", "meaning": "twenty thousand", "reading": "にまん", "chapter": "1", "subchapter": "2"},
    {"kanji": "三万", "meaning": "thirty thousand", "reading": "さんまん", "chapter": "1", "subchapter": "2"},
    {"kanji": "四万", "meaning": "forty thousand", "reading": "よんまん", "chapter": "1", "subchapter": "2"},
    {"kanji": "五万", "meaning": "fifty thousand", "reading": "ごまん", "chapter": "1", "subchapter": "2"},
    {"kanji": "六万", "meaning": "sixty thousand", "reading": "ろくまん", "chapter": "1", "subchapter": "2"},
    {"kanji": "七万", "meaning": "seventy thousand", "reading": "ななまん", "chapter": "1", "subchapter": "2"},
    {"kanji": "八万", "meaning": "eighty thousand", "reading": "はちまん", "chapter": "1", "subchapter": "2"},
    {"kanji": "九万", "meaning": "ninety thousand", "reading": "きゅうまん", "chapter": "1", "subchapter": "2"},
    {"kanji": "十万", "meaning": "hundred thousand", "reading": "じゅうまん", "chapter": "1", "subchapter": "2"},
    {"kanji": "百万", "meaning": "one million", "reading": "ひゃくまん", "chapter": "1", "subchapter": "2"},
    {"kanji": "円", "meaning": "yen", "reading": "えん", "chapter": "1", "subchapter": "2"},
    {"kanji": "百円", "meaning": "one hundred yen", "reading": "ひゃくえん", "chapter": "1", "subchapter": "2"},
    {"kanji": "千円", "meaning": "one thousand yen", "reading": "せんえん", "chapter": "1", "subchapter": "2"},
    {"kanji": "口", "meaning": "mouth", "reading": "くち", "chapter": "1", "subchapter": "2"},
    {"kanji": "目", "meaning": "eye", "reading": "め", "chapter": "1", "subchapter": "2"},
    {"kanji": "日", "meaning": "day", "reading": "にち", "chapter": "2", "subchapter": "1"},
    {"kanji": "月", "meaning": "moon", "reading": "つき", "chapter": "2", "subchapter": "1"},
    {"kanji": "火", "meaning": "fire", "reading": "ひ", "chapter": "2", "subchapter": "1"},
    {"kanji": "水", "meaning": "water", "reading": "みず", "chapter": "2", "subchapter": "1"},
    {"kanji": "木", "meaning": "tree", "reading": "き", "chapter": "2", "subchapter": "1"},
    {"kanji": "お金", "meaning": "money", "reading": "おかね", "chapter": "2", "subchapter": "1"},
    {"kanji": "日曜日", "meaning": "Sunday", "reading": "にちようび", "chapter": "2", "subchapter": "1"},
    {"kanji": "月曜日", "meaning": "Monday", "reading": "ついたち", "chapter": "2", "subchapter": "1"},
    {"kanji": "火曜日", "meaning": "Tuesday", "reading": "かようび", "chapter": "2", "subchapter": "1"},
    {"kanji": "水曜日", "meaning": "Wednesday", "reading": "すいようび", "chapter": "2", "subchapter": "1"},
    {"kanji": "木曜日", "meaning": "Thursday", "reading": "もくようび", "chapter": "2", "subchapter": "1"},
    {"kanji": "金曜日", "meaning": "Friday", "reading": "きんようび", "chapter": "2", "subchapter": "1"},
    {"kanji": "土曜日", "meaning": "Saturday", "reading": "どようび", "chapter": "2", "subchapter": "1"},
    {"kanji": "曜日", "meaning": "day of the week", "reading": "ようび", "chapter": "2", "subchapter": "1"},
    {"kanji": "一月", "meaning": "January", "reading": "いちがつ", "chapter": "2", "subchapter": "1"},
    {"kanji": "二月", "meaning": "February", "reading": "にがつ", "chapter": "2", "subchapter": "1"},
    {"kanji": "三月", "meaning": "March", "reading": "さんがつ", "chapter": "2", "subchapter": "1"},
    {"kanji": "四月", "meaning": "April", "reading": "しがつ", "chapter": "2", "subchapter": "1"},
    {"kanji": "五月", "meaning": "May", "reading": "ごがつ", "chapter": "2", "subchapter": "1"},
    {"kanji": "六月", "meaning": "June", "reading": "ろくがつ", "chapter": "2", "subchapter": "1"},
    {"kanji": "七月", "meaning": "July", "reading": "しちがつ", "chapter": "2", "subchapter": "1"},
    {"kanji": "八月", "meaning": "August", "reading": "はちがつ", "chapter": "2", "subchapter": "1"},
    {"kanji": "九月", "meaning": "September", "reading": "くがつ", "chapter": "2", "subchapter": "1"},
    {"kanji": "十月", "meaning": "October", "reading": "じゅうがつ", "chapter": "2", "subchapter": "1"},
    {"kanji": "十一月", "meaning": "November", "reading": "じゅういちがつ", "chapter": "2", "subchapter": "1"},
    {"kanji": "十二月", "meaning": "December", "reading": "じゅうにがつ", "chapter": "2", "subchapter": "1"},
    {"kanji": "本", "meaning": "book", "reading": "ほん", "chapter": "2", "subchapter": "2"},
    {"kanji": "日本", "meaning": "Japan", "reading": "にほん", "chapter": "2", "subchapter": "2"},
    {"kanji": "一本", "meaning": "one long object", "reading": "いっぽん", "chapter": "2", "subchapter": "2"},
    {"kanji": "二本", "meaning": "two long objects", "reading": "にほん", "chapter": "2", "subchapter": "2"},
    {"kanji": "三本", "meaning": "three long objects", "reading": "さんぽん", "chapter": "2", "subchapter": "2"},
    {"kanji": "四本", "meaning": "four long objects", "reading": "よんぽん", "chapter": "2", "subchapter": "2"},
    {"kanji": "五本", "meaning": "five long objects", "reading": "ごぽん", "chapter": "2", "subchapter": "2"},
    {"kanji": "六本", "meaning": "six long objects", "reading": "ろくぽん", "chapter": "2", "subchapter": "2"},
    {"kanji": "七本", "meaning": "seven long objects", "reading": "ななぽん", "chapter": "2", "subchapter": "2"},
    {"kanji": "八本", "meaning": "eight long objects", "reading": "はっぽん", "chapter": "2", "subchapter": "2"},
    {"kanji": "九本", "meaning": "nine long objects", "reading": "きゅうぽん", "chapter": "2", "subchapter": "2"},
    {"kanji": "十本", "meaning": "ten long objects", "reading": "じゅうぽん", "chapter": "2", "subchapter": "2"},
    {"kanji": "一時", "meaning": "one o'clock", "reading": "いちじ", "chapter": "2", "subchapter": "2"},
    {"kanji": "二時", "meaning": "two o'clock", "reading": "にじ", "chapter": "2", "subchapter": "2"},
    {"kanji": "三時", "meaning": "three o'clock", "reading": "さんじ", "chapter": "2", "subchapter": "2"},
    {"kanji": "四時", "meaning": "four o'clock", "reading": "よじ", "chapter": "2", "subchapter": "2"},
    {"kanji": "五時", "meaning": "five o'clock", "reading": "ごじ", "chapter": "2", "subchapter": "2"},
    {"kanji": "六時", "meaning": "six o'clock", "reading": "ろくじ", "chapter": "2", "subchapter": "2"},
    {"kanji": "七時", "meaning": "seven o'clock", "reading": "ななじ", "chapter": "2", "subchapter": "2"},
    {"kanji": "八時", "meaning": "eight o'clock", "reading": "はちじ", "chapter": "2", "subchapter": "2"},
    {"kanji": "九時", "meaning": "nine o'clock", "reading": "きゅうじ", "chapter": "2", "subchapter": "2"},
    {"kanji": "十時", "meaning": "ten o'clock", "reading": "じゅうじ", "chapter": "2", "subchapter": "2"},
    {"kanji": "十一時", "meaning": "eleven o'clock", "reading": "じゅういちじ", "chapter": "2", "subchapter": "2"},
    {"kanji": "十二時", "meaning": "twelve o'clock", "reading": "じゅうにじ", "chapter": "2", "subchapter": "2"},
    {"kanji": "人", "meaning": "person", "reading": "ひと", "chapter": "2", "subchapter": "2"},
    {"kanji": "日本人", "meaning": "Japanese person", "reading": "にほんじん", "chapter": "2", "subchapter": "2"},
    {"kanji": "一人", "meaning": "one person", "reading": "ひとり", "chapter": "2", "subchapter": "2"},
    {"kanji": "二人", "meaning": "two people", "reading": "ふたり", "chapter": "2", "subchapter": "2"},
    {"kanji": "三人", "meaning": "three people", "reading": "さんにん", "chapter": "2", "subchapter": "2"},
    {"kanji": "四人", "meaning": "four people", "reading": "よにん", "chapter": "2", "subchapter": "2"},
    {"kanji": "五人", "meaning": "five people", "reading": "ごにん", "chapter": "2", "subchapter": "2"},
    {"kanji": "一人で", "meaning": "alone", "reading": "ひとりで", "chapter": "2", "subchapter": "2"},
    {"kanji": "今", "meaning": "now", "reading": "いま", "chapter": "2", "subchapter": "2"},
    {"kanji": "今月", "meaning": "this month", "reading": "こんげつ", "chapter": "2", "subchapter": "2"},
    {"kanji": "今日", "meaning": "today", "reading": "きょう", "chapter": "2", "subchapter": "2"},
    {"kanji": "一時半", "meaning": "one thirty", "reading": "いちじはん", "chapter": "2", "subchapter": "2"},
    {"kanji": "二時半", "meaning": "two thirty", "reading": "にじはん", "chapter": "2", "subchapter": "2"},
    {"kanji": "三時半", "meaning": "three thirty", "reading": "さんじはん", "chapter": "2", "subchapter": "2"},
    {"kanji": "五分", "meaning": "five minutes", "reading": "ごふん", "chapter": "2", "subchapter": "2"},
    {"kanji": "十分", "meaning": "ten minutes", "reading": "じゅうふん", "chapter": "2", "subchapter": "2"},
    {"kanji": "半分", "meaning": "half", "reading": "はんぶん", "chapter": "2", "subchapter": "2"},
    {"kanji": "分かる", "meaning": "to understand", "reading": "わかる", "chapter": "2", "subchapter": "2"},
    {"kanji": "上", "meaning": "up", "reading": "うえ", "chapter": "3", "subchapter": "1"},
    {"kanji": "上げる", "meaning": "to raise", "reading": "あげる", "chapter": "3", "subchapter": "1"},
    {"kanji": "下", "meaning": "down", "reading": "した", "chapter": "3", "subchapter": "1"},
    {"kanji": "下げる", "meaning": "to lower", "reading": "さげる", "chapter": "3", "subchapter": "1"},
    {"kanji": "中", "meaning": "middle", "reading": "なか", "chapter": "3", "subchapter": "1"},
    {"kanji": "外", "meaning": "outside", "reading": "そと", "chapter": "3", "subchapter": "1"},
    {"kanji": "右", "meaning": "right", "reading": "みぎ", "chapter": "3", "subchapter": "1"},
    {"kanji": "左", "meaning": "left", "reading": "ひだり", "chapter": "3", "subchapter": "1"},
    {"kanji": "前", "meaning": "front", "reading": "まえ", "chapter": "3", "subchapter": "1"},
    {"kanji": "後ろ", "meaning": "back", "reading": "うしろ", "chapter": "3", "subchapter": "1"},
    {"kanji": "〜の後", "meaning": "after", "reading": "〜のあと", "chapter": "3", "subchapter": "1"},
    {"kanji": "後で", "meaning": "later", "reading": "あとで", "chapter": "3", "subchapter": "1"},
    {"kanji": "午前", "meaning": "morning", "reading": "ごぜん", "chapter": "3", "subchapter": "2"},
    {"kanji": "午後", "meaning": "afternoon", "reading": "ごご", "chapter": "3", "subchapter": "1"},
    {"kanji": "午前中", "meaning": "in the morning", "reading": "ごぜんちゅう", "chapter": "3", "subchapter": "2"},
    {"kanji": "門", "meaning": "gate", "reading": "もん", "chapter": "3", "subchapter": "2"},
    {"kanji": "間", "meaning": "between", "reading": "あいだ", "chapter": "3", "subchapter": "2"},
    {"kanji": "時間", "meaning": "time", "reading": "じかん", "chapter": "3", "subchapter": "2"},
    {"kanji": "一時間", "meaning": "one hour", "reading": "いちじかん", "chapter": "3", "subchapter": "2"},
    {"kanji": "二時間", "meaning": "two hours", "reading": "にじかん", "chapter": "3", "subchapter": "2"},
    {"kanji": "三時間", "meaning": "three hours", "reading": "さんじかん", "chapter": "3", "subchapter": "2"},
    {"kanji": "四時間", "meaning": "four hours", "reading": "よんじかん", "chapter": "3", "subchapter": "2"},
    {"kanji": "五時間", "meaning": "five hours", "reading": "ごじかん", "chapter": "3", "subchapter": "2"},
    {"kanji": "六時間", "meaning": "six hours", "reading": "ろくじかん", "chapter": "3", "subchapter": "2"},
    {"kanji": "七時間", "meaning": "seven hours", "reading": "ななじかん", "chapter": "3", "subchapter": "2"},
    {"kanji": "八時間", "meaning": "eight hours", "reading": "はちじかん", "chapter": "3", "subchapter": "2"},
    {"kanji": "九時間", "meaning": "nine hours", "reading": "きゅうじかん", "chapter": "3", "subchapter": "2"},
    {"kanji": "東", "meaning": "east", "reading": "ひがし", "chapter": "3", "subchapter": "2"},
    {"kanji": "東口", "meaning": "east exit", "reading": "ひがしぐち", "chapter": "3", "subchapter": "2"},
    {"kanji": "中東", "meaning": "middle east", "reading": "なかひがし", "chapter": "3", "subchapter": "2"},
    {"kanji": "西", "meaning": "west", "reading": "さい", "chapter": "3", "subchapter": "2"},
    {"kanji": "西口", "meaning": "west exit", "reading": "さいぐち", "chapter": "3", "subchapter": "2"},
    {"kanji": "南", "meaning": "south", "reading": "みなみ", "chapter": "3", "subchapter": "2"},
    {"kanji": "南口", "meaning": "south exit", "reading": "みなみぐち", "chapter": "3", "subchapter": "2"},
    {"kanji": "南東", "meaning": "southeast", "reading": "なんとう", "chapter": "3", "subchapter": "2"},
    {"kanji": "北", "meaning": "north", "reading": "きた", "chapter": "3", "subchapter": "2"},
    {"kanji": "北口", "meaning": "north exit", "reading": "きたぐち", "chapter": "3", "subchapter": "2"},
];